# -*- coding: utf-8 -*-
"""customer_service_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aX8BKFvU4Hsw2gY9h8hufDw-E0rt08ea
"""

!pip install datasets transformers --quiet

import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, ConfusionMatrixDisplay)
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported successfully!")

from datasets import load_dataset

# Bitext Customer Support Intent Dataset - 27 intents, ~26k samples
dataset = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset")

# Convert to pandas
df = pd.DataFrame(dataset['train'])

print("✅ Dataset downloaded successfully!")
print(f"📊 Shape: {df.shape}")
print(f"\n🔍 Columns: {df.columns.tolist()}")
print(f"\n📋 Sample Data:")
df.head()

print("=" * 55)
print("       📊 DATASET OVERVIEW")
print("=" * 55)

print(f"\n✅ Total Samples     : {len(df)}")
print(f"✅ Total Columns     : {len(df.columns)}")
print(f"✅ Unique Intents    : {df['intent'].nunique()}")
print(f"✅ Unique Categories : {df['category'].nunique()}")

print("\n📌 All Intent Categories:")
print(df['category'].value_counts())

print("\n📌 All Intent Labels:")
print(df['intent'].value_counts())

# Visualize intent distribution
plt.figure(figsize=(14, 6))
df['intent'].value_counts().plot(kind='bar', color='steelblue', edgecolor='black')
plt.title('📊 Intent Distribution in Dataset', fontsize=14)
plt.xlabel('Intent')
plt.ylabel('Number of Samples')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Category pie chart
plt.figure(figsize=(8, 8))
df['category'].value_counts().plot(kind='pie', autopct='%1.1f%%', startangle=140)
plt.title('🥧 Category Distribution', fontsize=14)
plt.ylabel('')
plt.tight_layout()
plt.show()

# Check actual column names in the dataset
print("📋 Columns:", df.columns.tolist())
print("\n🔍 First row:")
print(df.iloc[0])

# =============================================
# STEP 4: Text Preprocessing (FIXED)
# =============================================

def preprocess_text(text):
    text = str(text).lower()                         # Lowercase
    text = re.sub(r'\{\{.*?\}\}', '', text)          # Remove {{placeholders}} like {{Order Number}}
    text = re.sub(r'\d+', '', text)                  # Remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()         # Remove extra spaces
    return text

# ✅ FIXED: use 'instruction' instead of 'utterance'
df['clean_text'] = df['instruction'].apply(preprocess_text)

print("✅ Text Preprocessing Complete!")
print("\n📌 Before vs After Cleaning:")
for i in range(3):
    print(f"\nOriginal : {df['instruction'].iloc[i]}")
    print(f"Cleaned  : {df['clean_text'].iloc[i]}")

print(f"\n🔍 Null values: {df['clean_text'].isnull().sum()}")
print(f"📏 Avg text length: {df['clean_text'].apply(len).mean():.1f} characters")

# =============================================
# STEP 5: Train-Test Split
# =============================================

X = df['clean_text']
y = df['intent']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,          # 80% train, 20% test
    random_state=42,
    stratify=y              # Maintain class balance
)

print("=" * 45)
print("     ✂️  TRAIN - TEST SPLIT")
print("=" * 45)
print(f"  Total Samples  : {len(df)}")
print(f"  Training Set   : {len(X_train)} ({len(X_train)/len(df)*100:.1f}%)")
print(f"  Testing Set    : {len(X_test)}  ({len(X_test)/len(df)*100:.1f}%)")
print(f"  Unique Intents : {y.nunique()}")
print("=" * 45)

# =============================================
# STEP 6: Train Multiple Models & Compare
# =============================================

# Define models with TF-IDF pipelines
models = {
    "Naive Bayes"         : Pipeline([('tfidf', TfidfVectorizer(max_features=5000)), ('clf', MultinomialNB())]),
    "Logistic Regression" : Pipeline([('tfidf', TfidfVectorizer(max_features=5000)), ('clf', LogisticRegression(max_iter=1000))]),
    "Linear SVM"          : Pipeline([('tfidf', TfidfVectorizer(max_features=5000)), ('clf', LinearSVC(max_iter=1000))])
}

results = {}

print("=" * 50)
print("       🏋️  MODEL TRAINING & EVALUATION")
print("=" * 50)

for name, model in models.items():
    # Train
    model.fit(X_train, y_train)

    # Evaluate
    train_acc = accuracy_score(y_train, model.predict(X_train))
    test_acc  = accuracy_score(y_test,  model.predict(X_test))

    results[name] = {'Train Accuracy': train_acc, 'Test Accuracy': test_acc}

    print(f"\n🔹 {name}")
    print(f"   Train Accuracy : {train_acc * 100:.2f}%")
    print(f"   Test  Accuracy : {test_acc  * 100:.2f}%")

print("\n✅ All models trained!")

# =============================================
# STEP 7: Accuracy Comparison Chart
# =============================================

results_df = pd.DataFrame(results).T * 100

results_df.plot(kind='bar', figsize=(10, 5), color=['#4C72B0', '#DD8452'],
                edgecolor='black', width=0.6)
plt.title('📊 Model Accuracy Comparison', fontsize=14)
plt.xlabel('Model')
plt.ylabel('Accuracy (%)')
plt.xticks(rotation=0)
plt.ylim(80, 100)
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

print(results_df.round(2).to_string())

# =============================================
# STEP 8: Best Model - Full Evaluation
# =============================================

# Pick best model by test accuracy
best_name = max(results, key=lambda x: results[x]['Test Accuracy'])
best_model = models[best_name]
y_pred = best_model.predict(X_test)

print(f"🏆 Best Model: {best_name}")
print(f"   Test Accuracy: {results[best_name]['Test Accuracy']*100:.2f}%")

print("\n📋 Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred, labels=best_model.classes_)
plt.figure(figsize=(18, 14))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap='Blues', xticks_rotation=90, ax=plt.gca(), colorbar=False)
plt.title(f'🗂️ Confusion Matrix — {best_name}', fontsize=14)
plt.tight_layout()
plt.show()

# =============================================
# STEP 9: Chatbot Response Engine
# =============================================

# Response templates per intent
responses = {
    "cancel_order"             : "I can help you cancel your order. Please provide your order ID and I'll process the cancellation right away.",
    "track_order"              : "To track your order, please share your order number and I'll fetch the latest status for you.",
    "change_order"             : "Sure! Please tell me your order ID and what changes you'd like to make.",
    "delivery_options"         : "We offer Standard (5-7 days), Express (2-3 days), and Same-Day delivery options.",
    "complaint"                : "I'm really sorry to hear that. Please describe the issue and I'll escalate it to our team immediately.",
    "contact_customer_service" : "You can reach our support team at support@example.com or call 1-800-EXAMPLE (Mon–Fri, 9AM–6PM).",
    "check_refund_policy"      : "Our refund policy allows returns within 30 days of purchase. Refunds are processed within 5-7 business days.",
    "get_refund"               : "I'll initiate your refund request. Please provide your order ID and reason for the refund.",
    "check_invoice"            : "I can pull up your invoice. Please provide your order ID or registered email address.",
    "payment_issue"            : "Sorry about the payment trouble! Please verify your card details or try a different payment method.",
    "review"                   : "Thank you for your feedback! We truly value your experience and will use it to improve.",
    "newsletter_subscription"  : "You can manage your newsletter preferences in Account Settings > Notifications.",
    "change_shipping_address"  : "To update your shipping address, please share your order ID and the new address details.",
    "create_account"           : "Creating an account is easy! Click 'Sign Up' on our homepage and follow the steps.",
    "delete_account"           : "To delete your account, go to Settings > Account > Delete Account, or I can guide you through it.",
    "edit_account"             : "You can edit your account details by going to Settings > Profile. Need help with anything specific?",
    "switch_account"           : "To switch accounts, log out and sign in with the other account credentials.",
    "recover_password"         : "Click 'Forgot Password' on the login page and follow the instructions sent to your email.",
    "registration_problems"    : "Having trouble registering? Make sure your email isn't already in use, then try again.",
    "place_order"              : "I'd be happy to help you place an order! What product are you looking for?",
    "set_up_shipping_address"  : "To add a shipping address, go to Account > Addresses > Add New Address.",
    "check_cancellation_fee"   : "Cancellation fees depend on when you cancel. Orders cancelled within 1 hour are free; after that, a small fee may apply.",
    "track_refund"             : "I can check your refund status. Please provide your order ID or refund reference number.",
    "contact_human_agent"      : "Connecting you to a human agent now. Average wait time is 3-5 minutes.",
    "check_payment_methods"    : "We accept Visa, MasterCard, American Express, PayPal, and UPI.",
    "check_invoice"            : "Please share your order ID and I'll retrieve your invoice instantly.",
    "delivery_period"          : "Standard delivery takes 5-7 business days. Express delivery takes 2-3 business days.",
}

DEFAULT_RESPONSE = "I'm sorry, I didn't quite understand that. Could you rephrase? Or type 'help' to see what I can assist with."

def chatbot_response(user_input):
    cleaned = preprocess_text(user_input)
    predicted_intent = best_model.predict([cleaned])[0]
    response = responses.get(predicted_intent, DEFAULT_RESPONSE)
    return predicted_intent, response

print("✅ Chatbot engine ready!")

# =============================================
# STEP 10: Interactive Chatbot Demo
# =============================================

print("=" * 55)
print("  🤖 CUSTOMER SERVICE CHATBOT — DEMO")
print("  Type 'quit' to exit")
print("=" * 55)

# Run 5 sample queries automatically
sample_queries = [
    "I want to cancel my order",
    "Where is my package?",
    "How do I get a refund?",
    "I forgot my password",
    "I want to talk to a human"
]

for query in sample_queries:
    intent, reply = chatbot_response(query)
    print(f"\n👤 User    : {query}")
    print(f"🔍 Intent  : {intent}")
    print(f"🤖 Bot     : {reply}")
    print("-" * 55)